# Copyright (c) 2025 The Brave Authors. All rights reserved.
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this file,
# You can obtain one at https://mozilla.org/MPL/2.0/.

import("//build/config/features.gni")

source_set("youtube_script_injector_renderer") {
  sources = [
    "video_surface_streamer_impl.cc",
    "video_surface_streamer_impl.h",
  ]

  deps = [
    "//base",
    "//brave/browser/android/youtube_script_injector:mojom",
    "//cc/layers",
    "//content/public/renderer",
    "//media/base",
    "//mojo/public/cpp/bindings",
    "//third_party/blink/public:blink",
    "//ui/gfx/geometry",
  ]
}