package org.chromium.chrome.browser.settings;

public final class PostHogEventKeys {
        public static final String APP_INSTALLED = "App Installed";
        public static final String APP_LAUNCHED = "App Launched";
        public static final String USER_SIGNED_UP = "User Signed Up";
        public static final String LOGOUT = "Logout";
        public static final String LOGIN = "Login"; // DONE
        public static final String SOCIAL_LOGIN_USED = "Social Login Used";
        public static final String PAGE_VISITED = "Page Visited";
        public static final String URL_ENTERED = "URL Entered";
        public static final String SEARCH_PERFORMED = "Search Performed";
        public static final String LINK_CLICKED = "Link Clicked";
        public static final String TAB_OPENED = "Tab Opened";
        public static final String AVG_TABS_OPENED_CONCURRENTLY = "Avg Tabs Opened Concurrently";
        public static final String INCOGNITO_TAB_OPENED = "Incognito Tab Opened";
        public static final String BOOKMARK_ADDED = "Bookmark Added";
        public static final String DOWNLOAD_INITIATED = "Download Initiated";
        public static final String DOWNLOAD_COMPLETED = "Download Completed";
        public static final String HOME_SHORTCUT_CLICKED = "Home Shortcut Clicked";
        public static final String QUICK_LINK_USED = "Quick Link Used";
        public static final String HISTORY_VIEWED = "History Viewed";
        public static final String DEVICE_BACK_BUTTON_USED = "Device Back Button Used";
        public static final String REFRESH_USED = "Refresh Used";
        public static final String DEVICE_DARK_LIGHT_MODE = "Device Dark/Light Mode";
        public static final String VOICE_SEARCH_USED = "Voice Search Used";
        public static final String KEYBOARD_LANGUAGE = "Keyboard Language";
        public static final String LANGUAGE_CHANGED = "Language Changed";       
        public static final String PROFILE_VIEWED = "Profile Viewed"; // DONE
        public static final String PROFILE_UPDATED = "Profile Updated";
        public static final String YTP_PREMIUM_CLICKED_ON_QUICKLINK = "YTP Premium Clicked on Quicklink"; // DONE
        public static final String YTP_PREMIUM_CLICKED_ON_HOME = "YTP Premium Clicked on Home"; // DONE
        public static final String FEED_CLICKED_ON = "Feed Clicked On";
        public static final String POST_CLICKED_ON = "Post Clicked On"; // DONE
        public static final String SCROLL_DEPTH_ON_FEED = "Scroll Depth on Feed";
        public static final String SHARE_LINK_CLICKED = "Share Link Clicked";
        public static final String COMMENTS_PRESENT_ON_VISITED_URL = "Comments Present on Visited URL";
        public static final String BOTTOM_SHEET_CLICKED = "Bottom Sheet Clicked"; // DONE
        public static final String CLICKED_TO_VIEW_REPLIES = "Clicked to View Replies"; // DONE
        public static final String CLICKED_TO_VIEW_REPLY2REPLY = "Clicked to View Reply2Reply"; // DONE
        public static final String COMMENT_REPLY_SHARE_CLICKED = "Comment/Reply Share Clicked"; // DONE
        public static final String COMMENTED = "Commented"; // DONE
        public static final String UPVOTE_RECEIVED_ON_COMMENT = "Upvote Received on Comment";
        public static final String DOWNVOTE_RECEIVED_ON_COMMENT = "Downvote Received on Comment";
        public static final String REPLY_RECEIVED_ON_COMMENT = "Reply Received on Comment";
        public static final String ACTIVITY_ON_COMMENT_OR_REPLY = "Activity on Comment or Reply";
        public static final String UPVOTE_GIVEN = "Upvote Given"; // DONE
        public static final String DOWNVOTE_GIVEN = "Downvote Given"; // DONE
        public static final String YOUTUBE_VISITED = "YouTube Visited"; // DONE
}
